// ─── SONG POOL ─────────────────────────────────────────────────────────────
// Edit this file to add, remove or correct songs.

// ─── SONG POOL (DEFAULTS) ────────────────────────────────────────────────────
// Edit this file to add, remove or correct songs.
// Fields: id, title, artist, genre, key, bpm, prog, energy(1-5), instr(['g','p','v'])
// Genres: Blues | Rock | Pop | Soul | Funk | R&B | Ballad | Reggae | Latin | Jazz | Country

// ─── DATA ───────────────────────────────────────────────────────────────────
const DEFAULTS = [
  {id:1,title:"The Thrill Is Gone",artist:"B.B. King",genre:"Blues",key:"Bm",bpm:90,prog:"i–IV–i–V–IV–i",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:2,title:"Stormy Monday",artist:"T-Bone Walker",genre:"Blues",key:"G",bpm:55,prog:"I–IV–I–V–IV–I",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:3,title:"Ain't No Sunshine",artist:"Bill Withers",genre:"Soul",key:"Am",bpm:79,prog:"i–III–VII–i",energy:3,instr:['eg','b','dr','k'],effort:2},
  {id:4,title:"Further On Up the Road",artist:"E. Clapton / B. Bland",genre:"Blues",key:"Em",bpm:58,prog:"I–IV–I–V–IV–I",energy:2,instr:['eg','b','dr'],effort:2},
  {id:5,title:"Tears in Heaven",artist:"Eric Clapton",genre:"Ballad",key:"A",bpm:64,prog:"I–V–vi–IV",energy:2,instr:['eg','b','dr'],effort:2},
  {id:6,title:"Sweet Home Chicago",artist:"Robert Johnson",genre:"Blues",key:"E",bpm:90,prog:"I–IV–I–V–IV–I",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:7,title:"I Put a Spell on You",artist:"Jay Hawkins",genre:"Blues",key:"Cm",bpm:68,prog:"i–i7–iv–V7",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:8,title:"Stand by Me",artist:"Ben E. King",genre:"Soul",key:"A",bpm:116,prog:"I–vi–IV–V",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:9,title:"Wonderful Tonight",artist:"Eric Clapton",genre:"Ballad",key:"G",bpm:96,prog:"I–V–IV–V",energy:2,instr:['eg','b','dr'],effort:2},
  {id:10,title:"House of the Rising Sun",artist:"The Animals",genre:"Rock",key:"Am",bpm:117,prog:"i–III–IV–VI–i",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:11,title:"Pride and Joy",artist:"SRV",genre:"Blues",key:"E",bpm:120,prog:"I–IV–I–V–IV–I",energy:5,instr:['eg','b','dr'],effort:2},
  {id:12,title:"Killing Me Softly",artist:"Roberta Flack",genre:"Soul",key:"Dm",bpm:123,prog:"ii–V–I–IV",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:13,title:"Lonely Avenue",artist:"Ray Charles",genre:"Blues",key:"Bb",bpm:84,prog:"I–IV–V–IV",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:14,title:"Mustang Sally",artist:"Wilson Pickett",genre:"Soul",key:"C",bpm:110,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:15,title:"Let the Good Times Roll",artist:"BB King",genre:"Blues",key:"C",bpm:100,prog:"I–IV–I–V–IV–I",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:16,title:"Midnight Hour",artist:"Wilson Pickett",genre:"Soul",key:"D",bpm:108,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:17,title:"Sitting on the Dock",artist:"Otis Redding",genre:"Soul",key:"G",bpm:104,prog:"I–IV–I–IV",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:18,title:"Have You Ever Loved a Woman",artist:"Freddie King",genre:"Blues",key:"F#",bpm:62,prog:"I–IV–I–V–IV–I",energy:3,instr:['eg','b','dr'],effort:2},
  {id:19,title:"Love in Vain",artist:"Robert Johnson",genre:"Blues",key:"Em",bpm:58,prog:"I–IV–I–V–IV–I",energy:2,instr:['eg','b','dr'],effort:2},
  {id:20,title:"Drift Away",artist:"Dobie Gray",genre:"Soul",key:"D",bpm:96,prog:"I–V–vi–IV",energy:3,instr:['eg','b','dr','k'],effort:2},
  {id:21,title:"The Sky Is Crying",artist:"Elmore James",genre:"Blues",key:"A",bpm:56,prog:"I–IV–I–V–IV–I",energy:2,instr:['eg','b','dr'],effort:2},
  {id:22,title:"Since I've Been Loving You",artist:"Led Zeppelin",genre:"Rock",key:"Cm",bpm:56,prog:"i–iv–i–V–iv–i",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:23,title:"Nobody Knows You (Down and Out)",artist:"Eric Clapton",genre:"Blues",key:"G",bpm:58,prog:"I–III–IV–iv–I–V",energy:2,instr:['eg','b','dr'],effort:2},
  {id:24,title:"Little Wing",artist:"Jimi Hendrix",genre:"Rock",key:"Em",bpm:70,prog:"i–VII–VI–V–IV",energy:2,instr:['eg','b','dr'],effort:2},
  {id:25,title:"Superstition",artist:"Stevie Wonder",genre:"Funk",key:"Eb",bpm:100,prog:"i–VII–i–VII",energy:5,instr:['eg','b','dr','k','sx'],effort:3},
  {id:26,title:"Every Day I Have the Blues",artist:"BB King",genre:"Blues",key:"Bb",bpm:112,prog:"I–IV–I–V–IV–I",energy:5,instr:['eg','b','dr','k','sx'],effort:3},
  {id:27,title:"If I Ain't Got You",artist:"Alicia Keys",genre:"Soul",key:"Dbm",bpm:74,prog:"i–VI–III–VII",energy:3,instr:['eg','b','dr','k'],effort:2},
  {id:28,title:"I'd Rather Go Blind",artist:"Etta James",genre:"Blues",key:"A",bpm:60,prog:"I–IV–I–V",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:29,title:"The Weight",artist:"The Band",genre:"Rock",key:"A",bpm:73,prog:"I–III–IV–I",energy:2,instr:['eg','b','dr'],effort:2},
  {id:30,title:"Cry to Me",artist:"Solomon Burke",genre:"Soul",key:"G",bpm:65,prog:"I–IV–V–I",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:31,title:"Key to the Highway",artist:"Big Bill Broonzy",genre:"Blues",key:"E",bpm:78,prog:"I–IV–I–V–IV–I",energy:3,instr:['eg','b','dr'],effort:2},
  {id:32,title:"Green Onions",artist:"Booker T. & the MGs",genre:"Funk",key:"F",bpm:92,prog:"I–IV–V (12-bar)",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:33,title:"All Your Love",artist:"Otis Rush",genre:"Blues",key:"Am",bpm:62,prog:"i7–iv7–v7",energy:3,instr:['eg','b','dr'],effort:2},
  {id:34,title:"Things That I Used to Do",artist:"Guitar Slim",genre:"Blues",key:"E",bpm:84,prog:"I–IV–V7",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:35,title:"Smokestack Lightning",artist:"Howlin' Wolf",genre:"Blues",key:"E",bpm:72,prog:"I–I–I–I (vamp)",energy:3,instr:['eg','b','dr','sx'],effort:3},
  {id:36,title:"Rock Me Baby",artist:"B.B. King",genre:"Blues",key:"G",bpm:88,prog:"I–IV–V (12-bar)",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:37,title:"I've Got a Woman",artist:"Ray Charles",genre:"Soul",key:"A",bpm:100,prog:"I6–V7–I6–IV7–I6",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:38,title:"Just the Two of Us",artist:"Bill Withers",genre:"Soul",key:"Db",bpm:68,prog:"Dbmaj7–C7–Fm7–Ebm7",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:39,title:"I'm Tore Down",artist:"Freddie King",genre:"Blues",key:"F",bpm:108,prog:"I–IV–I–V–IV–I",energy:5,instr:['eg','b','dr'],effort:2},
  {id:40,title:"The Sky Is Crying",artist:"Albert King",genre:"Blues",key:"Bb",bpm:58,prog:"i–IV–i–V–IV–i",energy:2,instr:['eg','b','dr','sx'],effort:3},
  {id:41,title:"Reconsider Baby",artist:"Lowell Fulson",genre:"Blues",key:"Bb",bpm:80,prog:"I–IV–I–V–IV–I",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:42,title:"Fake Plastic Trees",artist:"Radiohead",genre:"Pop",key:"Dm",bpm:65,prog:"I–V–vi–IV",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:43,title:"Someone Like You",artist:"Adele",genre:"Ballad",key:"A",bpm:68,prog:"I–V–vi–IV",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:44,title:"Hallelujah",artist:"Leonard Cohen",genre:"Ballad",key:"C",bpm:60,prog:"I–V–I–V",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:45,title:"Black Hole Sun",artist:"Soundgarden",genre:"Rock",key:"Cm",bpm:70,prog:"i–VI–VII–VI",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:46,title:"Layla",artist:"Eric Clapton",genre:"Rock",key:"Dm",bpm:76,prog:"i–VII–i–VII",energy:3,instr:['eg','b','dr','k'],effort:2},
  {id:47,title:"November Rain",artist:"Guns N' Roses",genre:"Rock",key:"F#m",bpm:80,prog:"I–IV–V–IV",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:48,title:"Zombie",artist:"The Cranberries",genre:"Rock",key:"Em",bpm:84,prog:"i–III–VII–i",energy:4,instr:['eg','b','dr','sx'],effort:3},
  {id:49,title:"Brown Eyed Girl",artist:"Van Morrison",genre:"Pop",key:"G",bpm:150,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:50,title:"Zombie Jamboree",artist:"Kid Creole",genre:"Reggae",key:"G",bpm:96,prog:"I–IV–V–IV",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:51,title:"Is This Love",artist:"Bob Marley",genre:"Reggae",key:"G",bpm:76,prog:"I–V–vi–IV",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:52,title:"Three Little Birds",artist:"Bob Marley",genre:"Reggae",key:"A",bpm:76,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:53,title:"Bésame Mucho",artist:"Consuelo Velazquez",genre:"Latin",key:"G",bpm:120,prog:"I–IV–V–IV",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:54,title:"Siboney",artist:"Ernesto Lecuona",genre:"Latin",key:"Dm",bpm:96,prog:"i–i–IV–V",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:55,title:"Tequila",artist:"The Champs",genre:"Latin",key:"A",bpm:128,prog:"I–IV–I–IV",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:56,title:"Summertime",artist:"George Gershwin",genre:"Jazz",key:"Am",bpm:52,prog:"i–V7–i–IV",energy:1,instr:['eg','b','dr','k','sx'],effort:3},
  {id:57,title:"All of Me",artist:"John Legend",genre:"Soul",key:"F#m",bpm:76,prog:"vi–IV–I–V",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:58,title:"Thinking Out Loud",artist:"Ed Sheeran",genre:"Ballad",key:"Bb",bpm:64,prog:"I–V–vi–IV",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:59,title:"Perfect",artist:"Ed Sheeran",genre:"Pop",key:"G",bpm:76,prog:"I–V–vi–IV",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:60,title:"Shape of You",artist:"Ed Sheeran",genre:"Pop",key:"C#m",bpm:96,prog:"I–V–vi–IV",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:61,title:"Hoochie Coochie Man",artist:"Muddy Waters",genre:"Blues",key:"Bb",bpm:113,prog:"I–I–I–V–I",energy:4,instr:['eg','b','dr','sx'],effort:3},
  {id:62,title:"Got My Mojo Working",artist:"Muddy Waters",genre:"Blues",key:"E",bpm:120,prog:"I–IV–V–IV",energy:5,instr:['eg','b','dr','k','sx'],effort:3},
  {id:63,title:"Help Me",artist:"Sonny Boy Williamson",genre:"Blues",key:"G",bpm:80,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k'],effort:2},
  {id:64,title:"Mannish Boy",artist:"Muddy Waters",genre:"Blues",key:"E",bpm:88,prog:"I–I–I–IV",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:65,title:"Five Long Years",artist:"Eddie Boyd",genre:"Blues",key:"F",bpm:96,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k'],effort:2},
  {id:66,title:"Shine On You Crazy Diamond",artist:"Pink Floyd",genre:"Rock",key:"Am",bpm:63,prog:"i–VII–VI–VII",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:67,title:"Bohemian Rhapsody",artist:"Queen",genre:"Rock",key:"Bb",bpm:55,prog:"IV–I–V–IV",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:68,title:"Comfortably Numb",artist:"Pink Floyd",genre:"Rock",key:"G#m",bpm:63,prog:"i–VI–III–VII",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:69,title:"Whole Lotta Love",artist:"Led Zeppelin",genre:"Rock",key:"Em",bpm:89,prog:"i–i–i–IV",energy:5,instr:['eg','b','dr','sx'],effort:3},
  {id:70,title:"My Generation",artist:"The Who",genre:"Rock",key:"G",bpm:128,prog:"I–IV–V–IV",energy:5,instr:['eg','b','dr','sx'],effort:3},
  {id:71,title:"Hey Jude",artist:"The Beatles",genre:"Pop",key:"C",bpm:76,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:72,title:"The Sound of Silence",artist:"Simon & Garfunkel",genre:"Pop",key:"Em",bpm:72,prog:"i–VI–III–VII",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:73,title:"Yesterday",artist:"The Beatles",genre:"Ballad",key:"F",bpm:68,prog:"IV–I–IV–I",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:74,title:"Blackbird",artist:"The Beatles",genre:"Pop",key:"G",bpm:76,prog:"I–V–vi–IV",energy:2,instr:['eg','b','dr'],effort:2},
  {id:75,title:"Pinball Wizard",artist:"The Who",genre:"Rock",key:"D",bpm:120,prog:"I–IV–V–IV",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:76,title:"Let It Be",artist:"The Beatles",genre:"Pop",key:"C",bpm:68,prog:"I–V–I–IV",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:77,title:"Bluesette",artist:"Toots Thielemans",genre:"Jazz",key:"Dm",bpm:120,prog:"i–VI–II–V",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:78,title:"Funky Chicken",artist:"Arthur Conley",genre:"Funk",key:"C",bpm:132,prog:"I–IV–I–V",energy:5,instr:['eg','b','dr','k','sx'],effort:3},
  {id:79,title:"Uptown Special",artist:"James Brown",genre:"Funk",key:"Dm",bpm:116,prog:"i–VII–i–IV",energy:5,instr:['eg','b','dr','k','sx'],effort:3},
  {id:80,title:"Flashlight",artist:"Parliament",genre:"Funk",key:"Fm",bpm:108,prog:"i–i–i–IV",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:81,title:"Sittin' on the Toilet",artist:"Jimmy Spheeris",genre:"Soul",key:"Em",bpm:76,prog:"i–VI–III–VII",energy:2,instr:['eg','b','dr','k'],effort:2},
  {id:82,title:"Let Me Down Easy",artist:"Steppenwolf",genre:"Soul",key:"Am",bpm:100,prog:"i–IV–i–V",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:83,title:"Sweet Child O' Mine",artist:"Guns N' Roses",genre:"Rock",key:"Dm",bpm:120,prog:"i–III–VII–i",energy:4,instr:['eg','b','dr'],effort:2},
  {id:84,title:"You Are So Beautiful",artist:"Joe Cocker",genre:"Soul",key:"Db",bpm:60,prog:"I–V–I–IV",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:85,title:"Respect",artist:"Aretha Franklin",genre:"Soul",key:"C",bpm:108,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:86,title:"Redemption Song",artist:"Bob Marley",genre:"Reggae",key:"G",bpm:76,prog:"I–V–vi–IV",energy:3,instr:['eg','b','dr'],effort:2},
  {id:87,title:"Girl from Ipanema",artist:"João Gilberto",genre:"Latin",key:"Dm",bpm:96,prog:"i–VI–III–VII",energy:2,instr:['eg','b','dr','k','sx'],effort:3},
  {id:88,title:"Man of Constant Sorrow",artist:"Old Crow Medicine Show",genre:"Country",key:"Am",bpm:100,prog:"i–III–VII–i",energy:3,instr:['eg','b','dr'],effort:2},
  {id:89,title:"Tell Me I'm Not Dreaming",artist:"Ray Parker Jr.",genre:"R&B",key:"G",bpm:100,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx'],effort:3},
  {id:90,title:"Sexual Healing",artist:"Marvin Gaye",genre:"R&B",key:"Em",bpm:96,prog:"i–VI–III–VII",energy:3,instr:['eg','b','dr','k','sx'],effort:3},
  {id:91,title:"Born Under a Bad Sign",artist:"Albert King",genre:"Blues",key:"C#m",bpm:92,prog:"i–IV–i–V",energy:4,instr:['eg','b','dr','k','sx','vo'],effort:3},
  {id:92,title:"Red House",artist:"Jimi Hendrix",genre:"Blues",key:"Bb",bpm:68,prog:"I–IV–V (12-bar)",energy:3,instr:['eg','b','dr','vo'],effort:3},
  {id:93,title:"The Sky Is Crying",artist:"Elmore James",genre:"Blues",key:"A",bpm:56,prog:"I–IV–I–V–IV–I",energy:2,instr:['eg','b','dr','vo'],effort:2},
  {id:94,title:"Crossroads",artist:"Cream",genre:"Blues",key:"A",bpm:132,prog:"I–IV–V (12-bar)",energy:5,instr:['eg','b','dr','vo'],effort:4},
  {id:95,title:"Mannish Boy",artist:"Muddy Waters",genre:"Blues",key:"E",bpm:88,prog:"I vamp",energy:4,instr:['eg','b','dr','sx','vo','bv'],effort:3},
  {id:96,title:"Sweet Little Angel",artist:"B.B. King",genre:"Blues",key:"Bb",bpm:76,prog:"i–iv–i–V",energy:3,instr:['eg','b','dr','k','vo'],effort:2},
  {id:97,title:"Dust My Broom",artist:"Elmore James",genre:"Blues",key:"E",bpm:132,prog:"I–IV–V (12-bar)",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:98,title:"Hoodoo Man Blues",artist:"Junior Wells",genre:"Blues",key:"F",bpm:88,prog:"I–IV–V (12-bar)",energy:4,instr:['eg','b','dr','sx','vo'],effort:3},
  {id:99,title:"Texas Flood",artist:"SRV",genre:"Blues",key:"G",bpm:52,prog:"I–IV–I–V–IV–I",energy:2,instr:['eg','b','dr','vo'],effort:3},
  {id:100,title:"I Can't Quit You Baby",artist:"Otis Rush",genre:"Blues",key:"F",bpm:76,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','vo'],effort:3},
  {id:101,title:"Messin' With the Kid",artist:"Junior Wells",genre:"Blues",key:"Bb",bpm:120,prog:"I–IV–V (12-bar)",energy:4,instr:['eg','b','dr','sx','vo'],effort:3},
  {id:102,title:"Boom Boom",artist:"John Lee Hooker",genre:"Blues",key:"E",bpm:92,prog:"I vamp",energy:4,instr:['eg','b','dr','vo'],effort:2},
  {id:103,title:"Wang Dang Doodle",artist:"Koko Taylor",genre:"Blues",key:"C",bpm:100,prog:"I–IV–V (12-bar)",energy:4,instr:['eg','b','dr','sx','vo','bv'],effort:3},
  {id:104,title:"Forty Days and Forty Nights",artist:"Muddy Waters",genre:"Blues",key:"Bb",bpm:76,prog:"I–IV–V (12-bar)",energy:3,instr:['eg','b','dr','k','vo'],effort:2},
  {id:105,title:"La Grange",artist:"ZZ Top",genre:"Rock",key:"A",bpm:164,prog:"I vamp–IV–V",energy:5,instr:['eg','b','dr','vo'],effort:4},
  {id:106,title:"Sultans of Swing",artist:"Dire Straits",genre:"Rock",key:"Dm",bpm:96,prog:"I–bVII–bVI–V",energy:3,instr:['eg','ag','b','dr','vo'],effort:2},
  {id:107,title:"Money for Nothing",artist:"Dire Straits",genre:"Rock",key:"G",bpm:134,prog:"I–bVII–IV",energy:5,instr:['eg','b','dr','k','vo','bv'],effort:4},
  {id:108,title:"Highway to Hell",artist:"AC/DC",genre:"Rock",key:"A",bpm:116,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','vo','bv'],effort:3},
  {id:109,title:"Back in Black",artist:"AC/DC",genre:"Rock",key:"E",bpm:96,prog:"I–IV–V",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:110,title:"Smoke on the Water",artist:"Deep Purple",genre:"Rock",key:"Gm",bpm:112,prog:"i–IV–bVI",energy:4,instr:['eg','b','dr','k','vo'],effort:3},
  {id:111,title:"Come Together",artist:"The Beatles",genre:"Rock",key:"Dm",bpm:82,prog:"I vamp",energy:3,instr:['eg','b','dr','vo'],effort:2},
  {id:112,title:"Paint It Black",artist:"Rolling Stones",genre:"Rock",key:"Cm",bpm:164,prog:"i–VII–VI–III",energy:5,instr:['eg','b','dr','k','vo'],effort:3},
  {id:113,title:"Gimme Shelter",artist:"Rolling Stones",genre:"Rock",key:"C#m",bpm:96,prog:"i–VI–VII–i",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:114,title:"All Along the Watchtower",artist:"Jimi Hendrix",genre:"Rock",key:"Am",bpm:116,prog:"i–VII–VI–VII",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:115,title:"Purple Haze",artist:"Jimi Hendrix",genre:"Rock",key:"E",bpm:108,prog:"I–III–IV",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:116,title:"Walk This Way",artist:"Aerosmith",genre:"Rock",key:"Am",bpm:124,prog:"I–IV–V",energy:4,instr:['eg','b','dr','vo','bv'],effort:4},
  {id:117,title:"Paranoid",artist:"Black Sabbath",genre:"Rock",key:"Em",bpm:164,prog:"I–bVII–bVI–I",energy:5,instr:['eg','b','dr','vo'],effort:4},
  {id:118,title:"More Than a Feeling",artist:"Boston",genre:"Rock",key:"D",bpm:104,prog:"I–bVII–IV–I",energy:4,instr:['eg','b','dr','vo','bv'],effort:3},
  {id:119,title:"Hotel California",artist:"Eagles",genre:"Rock",key:"Bm",bpm:75,prog:"i–VI–III–VII",energy:3,instr:['eg','ag','b','dr','k','vo','bv'],effort:2},
  {id:120,title:"Stairway to Heaven",artist:"Led Zeppelin",genre:"Rock",key:"Am",bpm:82,prog:"i–VII–VI–VII",energy:3,instr:['ag','eg','b','dr','k','vo'],effort:3},
  {id:121,title:"Billie Jean",artist:"Michael Jackson",genre:"Pop",key:"F#m",bpm:117,prog:"i–III–VI–IV",energy:4,instr:['eg','b','dr','k','sx','vo','bv'],effort:3},
  {id:122,title:"Don't Stop Me Now",artist:"Queen",genre:"Pop",key:"F",bpm:156,prog:"I–V–vi–IV",energy:5,instr:['eg','b','dr','k','vo'],effort:4},
  {id:123,title:"I Will Always Love You",artist:"Whitney Houston",genre:"Pop",key:"Ab",bpm:60,prog:"I–V–vi–IV",energy:2,instr:['k','vo','bv'],effort:1},
  {id:124,title:"Sweet Caroline",artist:"Neil Diamond",genre:"Pop",key:"A",bpm:64,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:125,title:"Africa",artist:"Toto",genre:"Pop",key:"Bb",bpm:93,prog:"I–V–vi–IV",energy:3,instr:['eg','b','dr','k','sx','vo','bv'],effort:3},
  {id:126,title:"Take On Me",artist:"A-ha",genre:"Pop",key:"A",bpm:168,prog:"I–V–vi–IV",energy:4,instr:['eg','b','dr','k','vo'],effort:3},
  {id:127,title:"Easy",artist:"Commodores",genre:"Pop",key:"Ab",bpm:72,prog:"I–IV–V",energy:2,instr:['eg','b','dr','k','vo'],effort:1},
  {id:128,title:"September",artist:"Earth Wind & Fire",genre:"Pop",key:"C",bpm:112,prog:"I–IV–I–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv','pc'],effort:5},
  {id:129,title:"Dancing Queen",artist:"ABBA",genre:"Pop",key:"A",bpm:100,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:130,title:"Livin' on a Prayer",artist:"Bon Jovi",genre:"Pop",key:"Em",bpm:100,prog:"i–VI–III–VII",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:131,title:"Don't You (Forget About Me)",artist:"Simple Minds",genre:"Pop",key:"Em",bpm:108,prog:"i–VI–III–VII",energy:4,instr:['eg','b','dr','k','vo'],effort:3},
  {id:132,title:"Come As You Are",artist:"Nirvana",genre:"Pop",key:"Fm",bpm:120,prog:"i–bVII–IV",energy:3,instr:['eg','b','dr','vo'],effort:3},
  {id:133,title:"Wonderwall",artist:"Oasis",genre:"Pop",key:"F#m",bpm:87,prog:"I–V–vi–IV",energy:3,instr:['ag','eg','b','dr','k','vo','bv'],effort:2},
  {id:134,title:"Try a Little Tenderness",artist:"Otis Redding",genre:"Soul",key:"C",bpm:72,prog:"I–vi–IV–V",energy:3,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:135,title:"Chain of Fools",artist:"Aretha Franklin",genre:"Soul",key:"C",bpm:100,prog:"I–I–IV–I",energy:4,instr:['eg','b','dr','k','sx','vo','bv'],effort:3},
  {id:136,title:"A Change Is Gonna Come",artist:"Sam Cooke",genre:"Soul",key:"Bb",bpm:78,prog:"I–IV–I–V",energy:3,instr:['b','dr','k','sx','tp','tb','vo','bv'],effort:2},
  {id:137,title:"People Get Ready",artist:"Curtis Mayfield",genre:"Soul",key:"Bb",bpm:68,prog:"I–IV–I–V",energy:2,instr:['eg','b','dr','k','vo','bv'],effort:1},
  {id:138,title:"In the Midnight Hour",artist:"Wilson Pickett",genre:"Soul",key:"D",bpm:104,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:139,title:"When a Man Loves a Woman",artist:"Percy Sledge",genre:"Soul",key:"Ab",bpm:60,prog:"I–V–IV–I",energy:2,instr:['eg','b','dr','k','sx','vo'],effort:2},
  {id:140,title:"Natural Woman",artist:"Aretha Franklin",genre:"Soul",key:"C",bpm:68,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:2},
  {id:141,title:"What's Going On",artist:"Marvin Gaye",genre:"Soul",key:"Eb",bpm:96,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:2},
  {id:142,title:"Let's Stay Together",artist:"Al Green",genre:"Soul",key:"Ab",bpm:72,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:2},
  {id:143,title:"Stop! In the Name of Love",artist:"The Supremes",genre:"Soul",key:"G",bpm:112,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:144,title:"My Girl",artist:"The Temptations",genre:"Soul",key:"C",bpm:104,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:145,title:"I Heard It Through the Grapevine",artist:"Marvin Gaye",genre:"Soul",key:"Am",bpm:112,prog:"i–IV–i–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:146,title:"Soul Man",artist:"Sam & Dave",genre:"Soul",key:"D",bpm:116,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:147,title:"Hold On I'm Coming",artist:"Sam & Dave",genre:"Soul",key:"E",bpm:120,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:148,title:"Give Up the Funk",artist:"Parliament",genre:"Funk",key:"C",bpm:100,prog:"I–IV–I–bVII",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv','pc'],effort:5},
  {id:149,title:"Thank You",artist:"Sly & the Family Stone",genre:"Funk",key:"E",bpm:102,prog:"I vamp",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:4},
  {id:150,title:"Jungle Boogie",artist:"Kool & the Gang",genre:"Funk",key:"Ab",bpm:118,prog:"i–bVII–i",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:151,title:"Brick House",artist:"Commodores",genre:"Funk",key:"Am",bpm:98,prog:"i–VII–bVI",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:152,title:"Play That Funky Music",artist:"Wild Cherry",genre:"Funk",key:"Am",bpm:104,prog:"i–VII–bVI",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:4},
  {id:153,title:"Get Up (I Feel Like Being a Sex Machine)",artist:"James Brown",genre:"Funk",key:"C",bpm:118,prog:"I vamp",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:5},
  {id:154,title:"Papa's Got a Brand New Bag",artist:"James Brown",genre:"Funk",key:"C",bpm:132,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:5},
  {id:155,title:"I Got You (I Feel Good)",artist:"James Brown",genre:"Funk",key:"D",bpm:144,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:5},
  {id:156,title:"Le Freak",artist:"Chic",genre:"Funk",key:"Am",bpm:120,prog:"i–VII–bVI",energy:5,instr:['eg','b','dr','k','vo','bv'],effort:4},
  {id:157,title:"Good Times",artist:"Chic",genre:"Funk",key:"Fm",bpm:120,prog:"i–VII",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:158,title:"Chameleon",artist:"Herbie Hancock",genre:"Funk",key:"Bb",bpm:100,prog:"i vamp",energy:4,instr:['eg','b','dr','k','sx','tp','tb'],effort:4},
  {id:159,title:"Fire",artist:"Ohio Players",genre:"Funk",key:"E",bpm:120,prog:"I vamp",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:160,title:"No Scrubs",artist:"TLC",genre:"R&B",key:"F#m",bpm:104,prog:"i–VI–III–VII",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:161,title:"Waterfalls",artist:"TLC",genre:"R&B",key:"Db",bpm:100,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:162,title:"End of the Road",artist:"Boyz II Men",genre:"R&B",key:"Bb",bpm:60,prog:"I–vi–IV–V",energy:2,instr:['k','vo','bv'],effort:1},
  {id:163,title:"I'll Make Love to You",artist:"Boyz II Men",genre:"R&B",key:"Bb",bpm:60,prog:"I–vi–IV–V",energy:2,instr:['k','vo','bv'],effort:1},
  {id:164,title:"Always Be My Baby",artist:"Mariah Carey",genre:"R&B",key:"C",bpm:108,prog:"I–vi–IV–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:165,title:"I Want It That Way",artist:"Backstreet Boys",genre:"R&B",key:"A",bpm:100,prog:"I–IV–V",energy:3,instr:['ag','k','vo','bv'],effort:1},
  {id:166,title:"Smooth",artist:"Santana ft. Rob Thomas",genre:"R&B",key:"Am",bpm:116,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','pc','vo'],effort:3},
  {id:167,title:"Maria Maria",artist:"Santana",genre:"R&B",key:"Am",bpm:72,prog:"i–VII–bVI–V",energy:3,instr:['eg','b','dr','k','pc','vo','bv'],effort:2},
  {id:168,title:"Let's Get It On",artist:"Marvin Gaye",genre:"R&B",key:"Eb",bpm:72,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','sx','vo','bv'],effort:2},
  {id:169,title:"Superfreak",artist:"Rick James",genre:"R&B",key:"Am",bpm:96,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','sx','tp','vo','bv'],effort:3},
  {id:170,title:"Unchained Melody",artist:"The Righteous Brothers",genre:"Ballad",key:"Ab",bpm:68,prog:"I–vi–IV–V",energy:2,instr:['k','vo','bv'],effort:1},
  {id:171,title:"My Way",artist:"Frank Sinatra",genre:"Ballad",key:"C",bpm:60,prog:"I–vi–IV–V",energy:2,instr:['k','sx','tp','tb','vo'],effort:2},
  {id:172,title:"The Rose",artist:"Bette Midler",genre:"Ballad",key:"C",bpm:68,prog:"I–V–vi–IV",energy:2,instr:['ag','k','vo'],effort:1},
  {id:173,title:"With or Without You",artist:"U2",genre:"Ballad",key:"D",bpm:110,prog:"I–V–vi–IV",energy:3,instr:['eg','b','dr','k','vo'],effort:2},
  {id:174,title:"Fix You",artist:"Coldplay",genre:"Ballad",key:"Eb",bpm:70,prog:"I–V–vi–IV",energy:2,instr:['ag','eg','b','dr','k','vo'],effort:2},
  {id:175,title:"Let Her Go",artist:"Passenger",genre:"Ballad",key:"G",bpm:77,prog:"I–V–vi–IV",energy:2,instr:['ag','vo'],effort:1},
  {id:176,title:"Skinny Love",artist:"Bon Iver",genre:"Ballad",key:"Ab",bpm:87,prog:"I–vi–IV",energy:2,instr:['ag','k','vo'],effort:1},
  {id:177,title:"Mad World",artist:"Tears for Fears",genre:"Ballad",key:"F#m",bpm:88,prog:"i–VI–III–VII",energy:2,instr:['k','vo'],effort:2},
  {id:178,title:"No Woman No Cry",artist:"Bob Marley",genre:"Reggae",key:"C",bpm:75,prog:"I–V–vi–IV",energy:3,instr:['eg','b','dr','k','sx','vo','bv'],effort:2},
  {id:179,title:"Buffalo Soldier",artist:"Bob Marley",genre:"Reggae",key:"E",bpm:78,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:180,title:"Stir It Up",artist:"Bob Marley",genre:"Reggae",key:"A",bpm:78,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','vo'],effort:2},
  {id:181,title:"Jamming",artist:"Bob Marley",genre:"Reggae",key:"Ab",bpm:80,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:182,title:"The Harder They Come",artist:"Jimmy Cliff",genre:"Reggae",key:"G",bpm:84,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','vo'],effort:2},
  {id:183,title:"Many Rivers to Cross",artist:"Jimmy Cliff",genre:"Reggae",key:"C",bpm:68,prog:"I–IV–I–V",energy:2,instr:['ag','k','vo','bv'],effort:2},
  {id:184,title:"Rivers of Babylon",artist:"The Melodians",genre:"Reggae",key:"G",bpm:76,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:185,title:"The Tide Is High",artist:"Blondie",genre:"Reggae",key:"G",bpm:88,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:186,title:"Could You Be Loved",artist:"Bob Marley",genre:"Reggae",key:"Bm",bpm:116,prog:"i–VII–VI–VII",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:187,title:"Oye Como Va",artist:"Santana",genre:"Latin",key:"Am",bpm:120,prog:"i–IV",energy:4,instr:['eg','b','dr','k','sx','tp','tb','pc','vo'],effort:4},
  {id:188,title:"La Bamba",artist:"Ritchie Valens",genre:"Latin",key:"C",bpm:140,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','pc','vo','bv'],effort:3},
  {id:189,title:"Guantanamera",artist:"Various",genre:"Latin",key:"C",bpm:100,prog:"I–IV–V",energy:3,instr:['ag','b','dr','k','pc','vo','bv'],effort:2},
  {id:190,title:"Quizás Quizás Quizás",artist:"Nat King Cole",genre:"Latin",key:"F",bpm:112,prog:"I–IV–V–I",energy:3,instr:['ag','b','k','pc','vo'],effort:2},
  {id:191,title:"Chan Chan",artist:"Buena Vista",genre:"Latin",key:"Am",bpm:96,prog:"i–VII–VI–V",energy:3,instr:['ag','b','k','pc','vo','bv'],effort:2},
  {id:192,title:"La Vida Es Un Carnaval",artist:"Celia Cruz",genre:"Latin",key:"G",bpm:132,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','pc','vo','bv'],effort:5},
  {id:193,title:"Bamboleo",artist:"Gipsy Kings",genre:"Latin",key:"Am",bpm:132,prog:"i–VII–bVI–V",energy:4,instr:['ag','b','dr','k','pc','vo','bv'],effort:3},
  {id:194,title:"Conga",artist:"Gloria Estefan",genre:"Latin",key:"Am",bpm:104,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','sx','tp','pc','vo','bv'],effort:4},
  {id:195,title:"Mambo No. 5",artist:"Lou Bega",genre:"Latin",key:"C",bpm:107,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','pc','vo'],effort:4},
  {id:196,title:"La Isla Bonita",artist:"Madonna",genre:"Latin",key:"F#m",bpm:90,prog:"i–VI–III–VII",energy:3,instr:['eg','ag','b','dr','k','pc','vo'],effort:2},
  {id:197,title:"Livin' la Vida Loca",artist:"Ricky Martin",genre:"Latin",key:"Cm",bpm:178,prog:"i–VII–bVI–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','pc','vo','bv'],effort:5},
  {id:198,title:"Fly Me to the Moon",artist:"Frank Sinatra",genre:"Jazz",key:"C",bpm:144,prog:"ii–V–I",energy:3,instr:['b','dr','k','sx','tp','vo'],effort:2},
  {id:199,title:"All of Me",artist:"Standard",genre:"Jazz",key:"C",bpm:200,prog:"I–vi–ii–V",energy:3,instr:['b','k','sx','tp','vo'],effort:3},
  {id:200,title:"Autumn Leaves",artist:"Standard",genre:"Jazz",key:"Gm",bpm:120,prog:"ii–V–I",energy:2,instr:['b','k','sx','tp','vo'],effort:2},
  {id:201,title:"Take the A Train",artist:"Duke Ellington",genre:"Jazz",key:"Bb",bpm:220,prog:"I–II7–ii–V",energy:4,instr:['b','dr','k','sx','tp','tb','bv'],effort:4},
  {id:202,title:"So What",artist:"Miles Davis",genre:"Jazz",key:"Dm",bpm:136,prog:"i–bII",energy:3,instr:['b','dr','k','sx','tp','tb'],effort:3},
  {id:203,title:"Georgia on My Mind",artist:"Ray Charles",genre:"Jazz",key:"F",bpm:60,prog:"I–vi–ii–V",energy:2,instr:['k','sx','tp','tb','vo'],effort:2},
  {id:204,title:"Blue Monk",artist:"Thelonious Monk",genre:"Jazz",key:"Bb",bpm:96,prog:"I–IV–V (blues)",energy:3,instr:['b','dr','k','sx','tp'],effort:3},
  {id:205,title:"Misty",artist:"Erroll Garner",genre:"Jazz",key:"Eb",bpm:72,prog:"I–IV–ii–V",energy:2,instr:['k','sx','tp','vo'],effort:1},
  {id:206,title:"Round Midnight",artist:"Thelonious Monk",genre:"Jazz",key:"Cm",bpm:60,prog:"i–ii–V–i",energy:2,instr:['b','dr','k','sx','tp'],effort:2},
  {id:207,title:"St. Thomas",artist:"Sonny Rollins",genre:"Jazz",key:"C",bpm:208,prog:"I–IV–V",energy:4,instr:['b','dr','k','sx','pc'],effort:3},
  {id:208,title:"Isn't She Lovely",artist:"Stevie Wonder",genre:"Jazz",key:"Db",bpm:170,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','vo'],effort:3},
  {id:209,title:"What a Wonderful World",artist:"Louis Armstrong",genre:"Jazz",key:"F",bpm:68,prog:"I–IV–I–V",energy:1,instr:['b','k','sx','tp','vo'],effort:1},
  {id:210,title:"Take Me Home Country Roads",artist:"John Denver",genre:"Country",key:"G",bpm:74,prog:"I–V–vi–IV",energy:3,instr:['ag','eg','b','dr','k','vo','bv'],effort:2},
  {id:211,title:"Friends in Low Places",artist:"Garth Brooks",genre:"Country",key:"Ab",bpm:84,prog:"I–V–IV",energy:3,instr:['ag','eg','b','dr','k','vo','bv'],effort:2},
  {id:212,title:"Ring of Fire",artist:"Johnny Cash",genre:"Country",key:"G",bpm:92,prog:"I–IV–V",energy:3,instr:['ag','b','dr','tp','vo','bv'],effort:2},
  {id:213,title:"Jolene",artist:"Dolly Parton",genre:"Country",key:"Cm",bpm:131,prog:"i–III–VII–i",energy:4,instr:['ag','eg','b','dr','vo'],effort:2},
  {id:214,title:"Wagon Wheel",artist:"Old Crow Medicine Show",genre:"Country",key:"G",bpm:76,prog:"I–V–vi–IV",energy:3,instr:['ag','eg','b','dr','vo','bv'],effort:2},
  {id:215,title:"Tennessee Whiskey",artist:"Chris Stapleton",genre:"Country",key:"A",bpm:60,prog:"I–vi–IV–V",energy:2,instr:['eg','b','dr','k','vo'],effort:2},
  {id:216,title:"The House That Built Me",artist:"Miranda Lambert",genre:"Country",key:"G",bpm:86,prog:"I–V–vi–IV",energy:2,instr:['ag','eg','b','dr','k','vo'],effort:2},
  {id:217,title:"Copperhead Road",artist:"Steve Earle",genre:"Country",key:"D",bpm:168,prog:"I–bVII–IV",energy:4,instr:['ag','eg','b','dr','vo'],effort:3},
  {id:218,title:"Rocky Top",artist:"Various",genre:"Country",key:"G",bpm:180,prog:"I–IV–V",energy:4,instr:['ag','eg','b','dr','vo','bv'],effort:3},
  {id:219,title:"Stayin' Alive",artist:"Bee Gees",genre:"Disco",key:"Fm",bpm:104,prog:"i–IV–i–V",energy:4,instr:['eg','b','dr','k','sx','vo','bv'],effort:4},
  {id:220,title:"Night Fever",artist:"Bee Gees",genre:"Disco",key:"Ab",bpm:110,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:221,title:"I Will Survive",artist:"Gloria Gaynor",genre:"Disco",key:"Am",bpm:117,prog:"i–III–VII–IV",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo'],effort:4},
  {id:222,title:"Boogie Wonderland",artist:"Earth Wind & Fire",genre:"Disco",key:"Am",bpm:124,prog:"i–VII–bVI–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv','pc'],effort:5},
  {id:223,title:"YMCA",artist:"Village People",genre:"Disco",key:"F",bpm:126,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:224,title:"Last Dance",artist:"Donna Summer",genre:"Disco",key:"Db",bpm:100,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','sx','vo'],effort:3},
  {id:225,title:"Hot Stuff",artist:"Donna Summer",genre:"Disco",key:"Gm",bpm:112,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','sx','vo'],effort:4},
  {id:226,title:"Car Wash",artist:"Rose Royce",genre:"Disco",key:"Am",bpm:108,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:227,title:"Blame It on the Boogie",artist:"Jackson 5",genre:"Disco",key:"Gm",bpm:116,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:228,title:"On the Radio",artist:"Donna Summer",genre:"Disco",key:"G",bpm:100,prog:"I–IV–I–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:229,title:"Funkytown",artist:"Lipps Inc",genre:"Disco",key:"Am",bpm:114,prog:"i–VII–bVI",energy:4,instr:['eg','b','dr','k','sx','vo'],effort:4},
  {id:230,title:"Copacabana",artist:"Barry Manilow",genre:"Disco",key:"Cm",bpm:120,prog:"i–VII–bVI–V",energy:3,instr:['eg','b','dr','k','sx','tp','tb','vo','bv','pc'],effort:4},
  {id:231,title:"Crazy in Love",artist:"Beyoncé",genre:"R&B Modern",key:"Bb",bpm:100,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:232,title:"Uptown Funk",artist:"Bruno Mars",genre:"R&B Modern",key:"Dm",bpm:115,prog:"i–bVII–bVI–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:5},
  {id:233,title:"Get Lucky",artist:"Daft Punk",genre:"R&B Modern",key:"F#m",bpm:116,prog:"i–III–VII–IV",energy:4,instr:['eg','b','dr','k','sx','vo','bv'],effort:3},
  {id:234,title:"Happy",artist:"Pharrell Williams",genre:"R&B Modern",key:"F",bpm:160,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:235,title:"Treasure",artist:"Bruno Mars",genre:"R&B Modern",key:"Bb",bpm:88,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:236,title:"Just the Way You Are",artist:"Bruno Mars",genre:"R&B Modern",key:"F",bpm:109,prog:"I–IV–vi–V",energy:3,instr:['eg','b','dr','k','sx','vo'],effort:2},
  {id:237,title:"Locked Out of Heaven",artist:"Bruno Mars",genre:"R&B Modern",key:"Cm",bpm:144,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','sx','vo','bv'],effort:4},
  {id:238,title:"Count on Me",artist:"Bruno Mars",genre:"R&B Modern",key:"C",bpm:75,prog:"I–IV–vi–V",energy:2,instr:['ag','k','vo'],effort:1},
  {id:239,title:"Valerie",artist:"Mark Ronson ft. Amy Winehouse",genre:"R&B Modern",key:"F",bpm:144,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:240,title:"Back to Black",artist:"Amy Winehouse",genre:"R&B Modern",key:"Dm",bpm:100,prog:"i–VII–bVI–V",energy:3,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:241,title:"Rehab",artist:"Amy Winehouse",genre:"R&B Modern",key:"F",bpm:100,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','sx','tp','tb','vo'],effort:3},
  {id:242,title:"Feeling Good",artist:"Nina Simone",genre:"R&B Modern",key:"Cm",bpm:72,prog:"i–bVII–bVI–V",energy:3,instr:['b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:243,title:"Higher Ground",artist:"Stevie Wonder",genre:"Funk/Soul",key:"Eb",bpm:80,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','vo'],effort:4},
  {id:244,title:"Living for the City",artist:"Stevie Wonder",genre:"Funk/Soul",key:"Eb",bpm:100,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','sx','vo'],effort:4},
  {id:245,title:"I Wish",artist:"Stevie Wonder",genre:"Funk/Soul",key:"Eb",bpm:90,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:246,title:"Shining Star",artist:"Earth Wind & Fire",genre:"Funk/Soul",key:"E",bpm:108,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv','pc'],effort:5},
  {id:247,title:"Fantasy",artist:"Earth Wind & Fire",genre:"Funk/Soul",key:"Bb",bpm:120,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv','pc'],effort:4},
  {id:248,title:"Mighty Love",artist:"The Spinners",genre:"Funk/Soul",key:"Fm",bpm:100,prog:"i–VII–bVI–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:249,title:"Sir Duke",artist:"Stevie Wonder",genre:"Funk/Soul",key:"B",bpm:152,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:5},
  {id:250,title:"Dance to the Music",artist:"Sly & The Family Stone",genre:"Funk/Soul",key:"G",bpm:120,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:251,title:"Everyday People",artist:"Sly & The Family Stone",genre:"Funk/Soul",key:"Bb",bpm:88,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:252,title:"That's the Way of the World",artist:"Earth Wind & Fire",genre:"Funk/Soul",key:"Gb",bpm:84,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:2},
  {id:253,title:"Express Yourself",artist:"Charles Wright",genre:"Funk/Soul",key:"C",bpm:95,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','vo','bv'],effort:3},
  {id:254,title:"Ain't No Mountain High Enough",artist:"Marvin Gaye & Tammi Terrell",genre:"Funk/Soul",key:"Eb",bpm:120,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:255,title:"Got to Give It Up",artist:"Marvin Gaye",genre:"Funk/Soul",key:"A",bpm:120,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','k','sx','tp','tb','vo','bv'],effort:3},
  {id:256,title:"De Música Ligera",artist:"Soda Stereo",genre:"Rock Latino",key:"G",bpm:110,prog:"I–IV–V",energy:5,instr:['eg','b','dr','vo','bv'],effort:4},
  {id:257,title:"Lamento Boliviano",artist:"Enanitos Verdes",genre:"Rock Latino",key:"Am",bpm:128,prog:"i–VII–VI–VII",energy:4,instr:['eg','b','dr','vo','bv'],effort:3},
  {id:258,title:"Persiana Americana",artist:"Soda Stereo",genre:"Rock Latino",key:"G",bpm:120,prog:"I–IV–V",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:259,title:"La Célula Que Explota",artist:"Caifanes",genre:"Rock Latino",key:"Cm",bpm:110,prog:"i–VII–VI–V",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:260,title:"Afuera",artist:"Caifanes",genre:"Rock Latino",key:"Dm",bpm:104,prog:"i–VII–VI–V",energy:3,instr:['eg','b','dr','vo'],effort:3},
  {id:261,title:"Triste Canción",artist:"El Tri",genre:"Rock Latino",key:"G",bpm:96,prog:"I–IV–V",energy:3,instr:['eg','ag','b','dr','vo'],effort:2},
  {id:262,title:"En la Ciudad de la Furia",artist:"Soda Stereo",genre:"Rock Latino",key:"Am",bpm:114,prog:"i–VII–VI–V",energy:4,instr:['eg','b','dr','k','vo'],effort:3},
  {id:263,title:"El Final",artist:"Rostros Ocultos",genre:"Rock Latino",key:"Dm",bpm:108,prog:"i–VII–VI–V",energy:4,instr:['eg','b','dr','vo','bv'],effort:4},
  {id:264,title:"Trátame Suavemente",artist:"Soda Stereo",genre:"Rock Latino",key:"F",bpm:80,prog:"I–IV–V",energy:2,instr:['ag','b','dr','vo'],effort:2},
  {id:265,title:"No Voy En Tren",artist:"Charly García",genre:"Rock Latino",key:"G",bpm:100,prog:"I–IV–V",energy:3,instr:['eg','k','b','dr','vo'],effort:3},
  {id:266,title:"Florecita Rockera",artist:"Aterciopelados",genre:"Rock Latino",key:"Cm",bpm:112,prog:"i–VII–VI–V",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:267,title:"La Muralla Verde",artist:"Enanitos Verdes",genre:"Rock Latino",key:"Am",bpm:108,prog:"i–VII–VI–V",energy:3,instr:['eg','b','dr','vo'],effort:3},
  {id:268,title:"Oye Mi Amor",artist:"Maná",genre:"Rock Latino",key:"A",bpm:122,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:269,title:"Rayando el Sol",artist:"Maná",genre:"Rock Latino",key:"G",bpm:72,prog:"I–V–vi–IV",energy:2,instr:['ag','b','dr','vo'],effort:2},
  {id:270,title:"Mariposa Traicionera",artist:"Maná",genre:"Rock Latino",key:"Am",bpm:88,prog:"i–VII–VI–V",energy:3,instr:['eg','b','dr','k','vo'],effort:2},
  {id:271,title:"Clavado en un Bar",artist:"Maná",genre:"Rock Latino",key:"G",bpm:126,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:4},
  {id:272,title:"Gimme Tha Power",artist:"Molotov",genre:"Rap Rock",key:"Am",bpm:132,prog:"i–VII–VI–V",energy:5,instr:['eg','b','dr','vo','bv'],effort:4},
  {id:273,title:"Voto Latino",artist:"Molotov",genre:"Rap Rock",key:"Am",bpm:128,prog:"i–VII–VI–V",energy:4,instr:['eg','b','dr','vo','bv'],effort:4},
  {id:274,title:"Puto",artist:"Molotov",genre:"Rap Rock",key:"Am",bpm:144,prog:"i–VII–VI–V",energy:5,instr:['eg','b','dr','vo','bv'],effort:5},
  {id:275,title:"Devuélveme a Mi Chica",artist:"Hombres G",genre:"Rock Latino",key:"D",bpm:138,prog:"I–IV–V",energy:4,instr:['eg','b','dr','vo','bv'],effort:3},
  {id:276,title:"El Baile y El Salón",artist:"Café Tacvba",genre:"Rock Latino",key:"G",bpm:112,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','vo'],effort:3},
  {id:277,title:"A Dios le Pido",artist:"Juanes",genre:"Rock Latino",key:"G",bpm:78,prog:"I–V–vi–IV",energy:3,instr:['ag','eg','b','dr','vo'],effort:2},
  {id:278,title:"Muriendo Lento",artist:"Moderatto ft. Belinda",genre:"Rock Latino",key:"Am",bpm:100,prog:"i–VII–VI–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:279,title:"17 Años",artist:"Los Ángeles Azules",genre:"Cumbia",key:"G",bpm:120,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','pc','vo','bv'],effort:2},
  {id:280,title:"Baila Esta Cumbia",artist:"Selena",genre:"Cumbia",key:"G",bpm:128,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','pc','vo','bv'],effort:3},
  {id:281,title:"Cómo Te Voy a Olvidar",artist:"Los Ángeles Azules",genre:"Cumbia",key:"G",bpm:118,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','pc','vo','bv'],effort:2},
  {id:282,title:"El Listón de Tu Pelo",artist:"Los Ángeles Azules",genre:"Cumbia",key:"G",bpm:120,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','pc','vo','bv'],effort:2},
  {id:283,title:"Como la Flor",artist:"Selena",genre:"Cumbia",key:"G",bpm:132,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','pc','vo','bv'],effort:3},
  {id:284,title:"Mis Sentimientos",artist:"Los Ángeles Azules ft. Ximena Sariñana",genre:"Cumbia",key:"Am",bpm:116,prog:"i–VII–VI–V",energy:3,instr:['eg','b','dr','k','pc','vo','bv'],effort:2},
  {id:285,title:"Nunca es Suficiente",artist:"Los Ángeles Azules ft. Natalia Lafourcade",genre:"Cumbia",key:"Bb",bpm:108,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','pc','vo','bv'],effort:2},
  {id:286,title:"Oye Mujer",artist:"Raymix",genre:"Cumbia",key:"G",bpm:122,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','pc','vo'],effort:2},
  {id:287,title:"Mi Cucu",artist:"La Sonora Dinamita",genre:"Cumbia",key:"G",bpm:130,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','pc','vo','bv'],effort:3},
  {id:288,title:"Mil Horas",artist:"Los Abuelos de la Nada",genre:"Cumbia",key:"G",bpm:124,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','pc','vo','bv'],effort:3},
  {id:289,title:"Provócame",artist:"Chayanne",genre:"Pop Latino",key:"G",bpm:130,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','sx','tp','vo','bv','pc'],effort:4},
  {id:290,title:"Vuela Vuela",artist:"Magneto",genre:"Pop Latino",key:"G",bpm:132,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:291,title:"La Chica de Humo",artist:"Emmanuel",genre:"Pop Latino",key:"Bb",bpm:92,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','vo'],effort:2},
  {id:292,title:"Despacito",artist:"Luis Fonsi ft. Daddy Yankee",genre:"Pop Latino",key:"Bm",bpm:89,prog:"i–VI–III–VII",energy:4,instr:['ag','b','dr','k','pc','vo','bv'],effort:3},
  {id:293,title:"Eres",artist:"Café Tacvba",genre:"Balada",key:"Bb",bpm:68,prog:"I–V–vi–IV",energy:2,instr:['ag','k','vo'],effort:1},
  {id:294,title:"Tu Cárcel",artist:"Los Bukis",genre:"Balada",key:"Bb",bpm:72,prog:"I–V–vi–IV",energy:2,instr:['ag','k','vo','bv'],effort:1},
  {id:295,title:"Temblando",artist:"Hombres G",genre:"Balada",key:"G",bpm:76,prog:"I–V–vi–IV",energy:2,instr:['ag','k','vo'],effort:1},
  {id:296,title:"Kumbala",artist:"Maldita Vecindad",genre:"Balada",key:"Dm",bpm:72,prog:"i–VII–VI–V",energy:2,instr:['ag','b','dr','vo'],effort:2},
  {id:297,title:"Suavemente",artist:"Elvis Crespo",genre:"Merengue",key:"F",bpm:196,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','sx','tp','pc','vo','bv'],effort:5},
  {id:298,title:"El Rey",artist:"Vicente Fernández",genre:"Ranchera",key:"C",bpm:88,prog:"I–IV–V",energy:4,instr:['ag','b','tp','tb','vo'],effort:3},
  {id:299,title:"Payaso de Rodeo",artist:"Caballo Dorado",genre:"Ranchera",key:"G",bpm:130,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:4},
  {id:300,title:"Danza Kuduro",artist:"Don Omar",genre:"Reggaetón",key:"Gm",bpm:115,prog:"i–VII–VI–V",energy:5,instr:['b','dr','k','vo','bv'],effort:4},
  {id:336,title:"Despacito (Reggaetón Version)",artist:"Luis Fonsi ft. Daddy Yankee",genre:"Reggaetón",key:"Bm",bpm:89,prog:"i–VI–III–VII",energy:4,instr:['ag','b','dr','k','pc','vo','bv'],effort:3},
  {id:302,title:"Tren al Sur",artist:"Los Prisioneros",genre:"Synth-Pop",key:"G",bpm:120,prog:"I–V–vi–IV",energy:3,instr:['k','b','dr','vo'],effort:2},
  {id:303,title:"Ni Tú Ni Nadie",artist:"Alaska y Dinarama",genre:"Synth-Pop",key:"Am",bpm:126,prog:"i–VII–VI–V",energy:3,instr:['k','b','dr','vo','bv'],effort:3},
  {id:304,title:"Matador",artist:"Los Fabulosos Cadillacs",genre:"Ska",key:"G",bpm:168,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','sx','tp','tb','vo','bv','pc'],effort:5},
  {id:305,title:"La Planta",artist:"Caos",genre:"Ska",key:"G",bpm:168,prog:"I–IV–V",energy:4,instr:['eg','b','dr','sx','tp','tb','vo','bv'],effort:4},
  {id:306,title:"Mr. Brightside",artist:"The Killers",genre:"Rock",key:"D",bpm:148,prog:"I–V–vi–IV",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:4},
  {id:307,title:"Creep",artist:"Radiohead",genre:"Rock",key:"G",bpm:93,prog:"I–III–IV–iv",energy:3,instr:['eg','b','dr','vo'],effort:2},
  {id:308,title:"Smells Like Teen Spirit",artist:"Nirvana",genre:"Rock",key:"Fm",bpm:116,prog:"i–IV–bIII–VI",energy:5,instr:['eg','b','dr','vo'],effort:4},
  {id:309,title:"Seven Nation Army",artist:"The White Stripes",genre:"Rock",key:"E",bpm:124,prog:"i–VII–VI–VII",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:310,title:"Basket Case",artist:"Green Day",genre:"Rock",key:"Eb",bpm:172,prog:"I–IV–V",energy:5,instr:['eg','b','dr','vo'],effort:4},
  {id:311,title:"Sex on Fire",artist:"Kings of Leon",genre:"Rock",key:"C",bpm:152,prog:"I–IV–I–V",energy:4,instr:['eg','b','dr','vo'],effort:3},
  {id:312,title:"It's My Life",artist:"Bon Jovi",genre:"Rock",key:"Ab",bpm:116,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:313,title:"You Shook Me All Night Long",artist:"AC/DC",genre:"Rock",key:"G",bpm:124,prog:"I–IV–V",energy:4,instr:['eg','b','dr','vo','bv'],effort:4},
  {id:314,title:"Should I Stay or Should I Go",artist:"The Clash",genre:"Rock",key:"G",bpm:112,prog:"I–IV–V",energy:4,instr:['eg','b','dr','vo','bv'],effort:3},
  {id:315,title:"Are You Gonna Be My Girl",artist:"Jet",genre:"Rock",key:"A",bpm:208,prog:"I–IV–V",energy:5,instr:['eg','b','dr','vo','bv'],effort:4},
  {id:316,title:"The Middle",artist:"Jimmy Eat World",genre:"Rock",key:"A",bpm:152,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:317,title:"All the Small Things",artist:"blink-182",genre:"Rock",key:"C",bpm:148,prog:"I–V–IV",energy:4,instr:['eg','b','dr','vo','bv'],effort:3},
  {id:318,title:"Boys Don't Cry",artist:"The Cure",genre:"Rock",key:"G",bpm:192,prog:"I–IV–V",energy:3,instr:['eg','k','b','dr','vo'],effort:2},
  {id:319,title:"Losing My Religion",artist:"R.E.M.",genre:"Rock",key:"Am",bpm:122,prog:"vi–IV–I–V",energy:3,instr:['ag','eg','b','dr','k','vo'],effort:2},
  {id:320,title:"Yellow",artist:"Coldplay",genre:"Rock",key:"B",bpm:88,prog:"I–V–vi–IV",energy:2,instr:['ag','b','dr','vo'],effort:2},
  {id:321,title:"Don't Look Back in Anger",artist:"Oasis",genre:"Rock",key:"C",bpm:82,prog:"I–IV–I–V",energy:3,instr:['ag','eg','b','dr','k','vo','bv'],effort:2},
  {id:322,title:"Sweet Home Alabama",artist:"Lynyrd Skynyrd",genre:"Rock",key:"D",bpm:96,prog:"I–bVII–IV",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:323,title:"Summer of '69",artist:"Bryan Adams",genre:"Rock",key:"D",bpm:140,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:324,title:"Don't Stop Believin'",artist:"Journey",genre:"Pop",key:"E",bpm:120,prog:"I–V–vi–IV",energy:5,instr:['eg','b','dr','k','vo','bv'],effort:4},
  {id:325,title:"I Gotta Feeling",artist:"Black Eyed Peas",genre:"Pop",key:"G",bpm:128,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:326,title:"Shut Up and Dance",artist:"WALK THE MOON",genre:"Pop",key:"E",bpm:128,prog:"I–V–vi–IV",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:327,title:"Can't Stop the Feeling!",artist:"Justin Timberlake",genre:"Pop",key:"C",bpm:113,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:328,title:"I Wanna Dance with Somebody",artist:"Whitney Houston",genre:"Pop",key:"Ab",bpm:118,prog:"I–IV–V",energy:4,instr:['b','dr','k','sx','tp','tb','vo','bv'],effort:4},
  {id:329,title:"Crazy Little Thing Called Love",artist:"Queen",genre:"Pop",key:"D",bpm:156,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:330,title:"I Want to Break Free",artist:"Queen",genre:"Pop",key:"Bb",bpm:106,prog:"I–IV–V",energy:3,instr:['eg','b','dr','k','vo','bv'],effort:2},
  {id:331,title:"Sweet Dreams (Are Made of This)",artist:"Eurythmics",genre:"Pop",key:"Am",bpm:130,prog:"i–VII–VI–V",energy:3,instr:['k','b','dr','vo'],effort:2},
  {id:332,title:"Mamma Mia",artist:"ABBA",genre:"Pop",key:"D",bpm:136,prog:"I–IV–V",energy:4,instr:['eg','b','dr','k','vo','bv'],effort:3},
  {id:333,title:"We Will Rock You",artist:"Queen",genre:"Pop",key:"A",bpm:80,prog:"I–IV–V",energy:4,instr:['eg','b','dr','vo','bv'],effort:3},
  {id:334,title:"La Chona",artist:"Los Tucanes de Tijuana",genre:"Disco",key:"G",bpm:134,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','tp','tb','pc','vo','bv'],effort:4},
  {id:335,title:"El Sonidito",artist:"Hechizeros Band",genre:"Disco",key:"G",bpm:132,prog:"I–IV–V",energy:5,instr:['eg','b','dr','k','tp','tb','pc','vo','bv'],effort:4}
];


// ─── SCHEMA VALIDATION ──────────────────────────────────────────────────────
function validateSong(s) {
  // Ensure all required fields exist with correct types
  if(!s || typeof s !== 'object') return null;
  return {
    id: parseInt(s.id) || Math.random() * 10000,
    title: String(s.title || '').trim() || 'Untitled',
    artist: String(s.artist || '').trim() || 'Unknown',
    genre: String(s.genre || 'Blues').trim(),
    key: String(s.key || 'C').trim(),
    bpm: Math.max(40, Math.min(250, parseInt(s.bpm) || 100)),
    prog: String(s.prog || 'I-IV-V').trim().slice(0, 40),
    energy: Math.min(5, Math.max(1, parseInt(s.energy) || 3)),
    effort: Math.min(5, Math.max(1, parseInt(s.effort) || 2)),
    instr: Array.isArray(s.instr) && s.instr.length 
      ? s.instr.filter(i => ['eg','ag','b','dr','k','sx','tp','tb','vo','bv','pc'].includes(i))
      : ['g'],
    note: String(s.note || '').trim()
  };
}

let pool = (()=>{
  try {
    const p = JSON.parse(localStorage.getItem('fmg-pool'));
    if(Array.isArray(p) && p.length > 0) {
      // Validate each song in loaded pool
      const validated = p.map(s => validateSong(s)).filter(s => s && s.title !== 'Untitled');
      return validated.length > 0 ? validated : DEFAULTS.map(validateSong);
    }
    return DEFAULTS.map(validateSong);
  } catch(e) { 
    console.warn('Pool load error, using DEFAULTS:', e);
    return DEFAULTS.map(validateSong);
  }
})();
let nights = (()=>{
  try {
    const n = JSON.parse(localStorage.getItem('fmg-nights'));
    return Array.isArray(n) ? n : [];
  } catch(e) { return []; }
})();
let sets = [];
let numSets = 3;
let instrs = JSON.parse(localStorage.getItem('fmg-instrs')||'null') || ['eg','b','dr','vo'];
let effortWeights = JSON.parse(localStorage.getItem('fmg-effort-weights') || 'null') || {eg:1.0, ag:0.8, b:1.2, dr:1.8, k:1.0, sx:1.5, tp:1.5, tb:1.5, vo:2.0, bv:1.5, pc:1.2};
let mustPlay = (()=>{
  try {
    const m = JSON.parse(localStorage.getItem('fmg-mustPlay') || '[]');
    return new Set(Array.isArray(m) ? m : []);
  } catch(e) { return new Set(); }
})();
let pf = 'all';
let selectedGenres = ['Blues', 'Rock', 'Pop', 'Soul', 'Funk', 'R&B', 'Ballad', 'Reggae', 'Latin', 'Jazz', 'Country', 'Disco', 'R&B Modern', 'Funk/Soul', 'Rock Latino', 'Cumbia', 'Pop Latino', 'Balada', 'Merengue', 'Ranchera', 'Reggaetón', 'Synth-Pop', 'Rap Rock', 'Ska'];
let editId = null;
let dragSrc = null;
// Safe nextId calculation - ensures auto-increment avoids collisions with DEFAULTS (max id:336)
let nextId = (() => {
  try {
    const maxId = pool.length ? Math.max(...pool.map(s => {
      const id = parseInt(s.id);
      return isFinite(id) ? id : 0;
    })) : 90;
    return Math.max(maxId + 1, 337); // 337 because last DEFAULTS id is 336
  } catch(e) { 
    console.warn('nextId calculation error:', e);
    return 337; 
  }
})();
let aiTab = 'lookup';
let apiProvider = localStorage.getItem('fmg-api-provider') || 'claude';
let apiKeys = {
  claude: localStorage.getItem('fmg-api-key-claude') || '',
  gemini: localStorage.getItem('fmg-api-key-gemini') || '',
  chatgpt: localStorage.getItem('fmg-api-key-chatgpt') || ''
};

// ─── TRANSLATIONS ────────────────────────────────────────────────────────────
// Add a new language: copy an existing block, change the key (e.g. 'fr'),
// add a lang button in index.html, and add 'fr' to the setLang() call.
// Keys marked PRESERVE are intentionally not translated (setlist, BPM, genre names, etc.)